### ISSUE TITLE
The Game (UI and Controller)

### ISSUE THREAD

**Issue by dershao** [DwangDistracted/Zombies-are-Vegan#43]

**Comment by dershao** [comment]
- Each grid is separated into a Plant and Zombies panel
- Zombie grid shows a maximum of 3 types of Zombies with the number of zombies on that grid
- More than 3 types will show a `...` which could be clicked to show a JOptionPane showing a full list of zombies
- Top level panel with resources, select-able plant types
- Left side column has clickable lawn mowers that nuke everything in that row (both Plants and Zombies) 
- JOptionPane at the beginning of game showing all the zombies that will be spawned in this level (potentially reusable with the JOptionPane from above)

**Comment by DwangDistracted** [comment]
The constructor for this needs a game object so that it can buld according to the level info

**Comment by DwangDistracted** [comment]
Since each Grid is the same in terms of UI, we should add a Grid extends JPanel Class to the ui package and use that in GameUI

**Comment by DwangDistracted** [comment]
Making a new Issue for the Grid Class
